### PR TITLE
Add tvOS support to podspec

### PR DESCRIPTION
**Pull request by chillpop**
- updated the podspec to support tvOS.
- created a tvOS target that runs the unit tests
- run the tvOS target on Travis
- removed unnecessary enum name to avoid duplicate symbols on tvOS

@vokal-isaac, code review when you have a moment?

### CODE REVIEW

**Comment by vokal-isaac** [comment]
Code LGTM, but Travis is unhappy (2 of the matrix-builds crashed; the third is still running, maybe).

**Comment by chillpop** [comment]
Oops. I had removed the before_script section of the travis file that updates xctool. Travis is green now.

**Comment by vokal-isaac** [comment]
Ahh, I should have called that out.  I'd assumed that was intentional.

LGTM.

**Comment by vokal-isaac** [comment]
green burns glow

**Comment by vokal-isaac** [comment]
Should we enable code coverage reporting in a future PR?

**Comment by chillpop** [comment]
tagged and `pod trunk push`'d

**Comment by chillpop** [comment]
sure, I'll add an issue

**Pull request merged**
