### PR TITLE
Change org name from VOKAL Interactive to Vokal

### PR DESCRIPTION
**Pull request by chillpop**
@vokal-isaac, @seanwolter.  I'm hoping this change will allow me to `pod trunk push` on the VOKMockURLProtocol repo.

### CODE REVIEW

**Comment by scottferg** [comment]
Update to 2015 while you're at it?

**Comment by chillpop** [comment]
Per @seanwolter comments here: https://github.com/vokal/VOKMockUrlProtocol/pull/20#discussion_r22775256
The date on the copyright could go either way (no date, first published date, or date range).

**Comment by seanwolter** [comment]
That unverified internet commenter that I cited recommended "undated, date of latest revision, or a date range", but the date doesn't really matter. Many sources say copyright law doesn't require a copyright notice after 1979. The notice is nice because then infringers can't say they were unaware.
In short: I don't care much and I'm not a lawyer.

**Comment by vokal-isaac** [comment]
Is this what @seanwolter meant about needing a pod update, or did he mean something in `VOKMockUrlProtocol`?

**Comment by vokal-isaac** [comment]
LGTM

**Comment by seanwolter** [comment]
I meant to `pod trunk push` VOKMockUrlProtocol you first had to pod update. 
In the VOKMockUrlProtocol folder do `pod update` before `pod trunk push`ing

**Comment by foresmac** [comment]
@seanwolter is right, technically anything created since 1979 that is legally protected by copyright is automatically copyright at the time it was created. Since the source of these evolves over time, a range is preferable here. The git history can serve as a technical record of the relevant dates for legal purposes, but as a courtesy to those using the code in a license-compliant way, it would be best to keep the copyright notice updated with a data range.

**Comment by seanwolter** [comment]
@chillpop You heard @foresmac . I'm pretty sure he *is* a lawyer. Date ranges it is!

**Comment by chillpop** [comment]
date ranges it is then.
I also ran `pod update` for the example projects.

**Comment by vokal-isaac** [comment]
:+1:

**Comment by chillpop** [comment]
tagged and `pod trunk push`ed

**Pull request merged**
